extends: default

rules:
  document-start: disable
  truthy: disable
  comments:
    min-spaces-from-content: 1
  line-length:
    max: 150
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
