name: Feature Request
description: Suggest an improvement or new feature
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea below.

  - type: dropdown
    id: type
    attributes:
      label: Request Type
      options:
        - New image template
        - Improvement to existing image
        - Workflow/CI improvement
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What would you like to see?
      placeholder: "Describe the feature..."
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Why do you need this? What problem does it solve?
      placeholder: "I need this because..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any workarounds?
      placeholder: "I've tried..."

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information (links, examples, etc.)
